name: Build and Push Docker Image

on:
  push:
    branches:
      - "main"
      - "dev"
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: djav1985/v-mcp-copilot-feedback
          flavor: latest=false
          tags: |
            # Tag main branch as :main
            type=raw,value=main,enable=${{ github.ref == 'refs/heads/main' }}
            # Tag dev branch as :dev
            type=raw,value=dev,enable=${{ github.ref == 'refs/heads/dev' }}
            # Tag commits with SHA
            type=sha,priority=100,enable=${{ github.event_name == 'push' }}
            # Tag releases with their version
            type=ref,event=tag

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
